version: "3.5"

x-environment: &default-back-environment
  # These environment variables will be used by taiga-back and taiga-async.
  # Database settings
  POSTGRES_DB: "taiga"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123"
  POSTGRES_HOST: "taiga-db"
  # Taiga settings
  TAIGA_SECRET_KEY: "j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl"
  TAIGA_SITES_SCHEME: "http"
  TAIGA_SITES_DOMAIN: "z4s4gkckkkkokc8gccwswwkgw.95.217.187.120.sslip.io"
  TAIGA_SUBPATH: ""
  # Email settings.
  EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
  DEFAULT_FROM_EMAIL: "no-reply@example.com"
  EMAIL_USE_TLS: "False"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: ""
  EMAIL_PORT: "25"
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""
  # Rabbitmq settings
  RABBITMQ_USER: "taiga"
  RABBITMQ_PASS: "taiga123"
  # Telemetry settings
  ENABLE_TELEMETRY: "false"
  PUBLIC_REGISTER_ENABLED: "True"  # Enables public registration in backend

x-volumes: &default-back-volumes
  # These volumens will be used by taiga-back and taiga-async.
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started
    labels:
      coolify.domain: "x48gc840o4wkkko0k4owog04.95.217.187.120.sslip.io"

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started
    labels:
      coolify.domain: "rocc4coeke040k0kk549g8ws.95.217.187.120.sslip.io"

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "taiga-async-rabbitmq-cookie"
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga123"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: "rccw4gwsgk0wc4csk0oswcg8.95.217.187.120.sslip.io"

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://z4s4gkckkkkokc8gccwswwkgw.95.217.187.120.sslip.io"
      TAIGA_WEBSOCKETS_URL: "ws://z4s44kw400sgc0g0008c0c4k.95.217.187.120.sslip.io"
      PUBLIC_REGISTER_ENABLED: "true"
    networks:
      - taiga
    labels:
      coolify.domain: "v0k0owoww00cgkg8gcgcsogs.95.217.187.120.sslip.io"

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: "taiga"
      RABBITMQ_PASS: "taiga123"
      TAIGA_SECRET_KEY: "j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl"
    networks:
      - taiga
    depends_on:
      taiga-events-rabbitmq:
        condition: service_started
    labels:
      coolify.domain: "z4s44kw400sgc0g0008c0c4k.95.217.187.120.sslip.io"

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "taiga-events-rabbitmq-cookie"
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga123"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: "m08k8440wo8ogo4osco4ow8s.95.217.187.120.sslip.io"

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "360"
      SECRET_KEY: "j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl"
    networks:
      - taiga
    labels:
      coolify.domain: "o8kg8gkgwws008wo4k848kc.95.217.187.120.sslip.io"

  # This is the main service that Coolify will use
  taiga-gateway:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
    networks:
      - taiga
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
    labels:
      coolify.managed: "true"
      coolify.default: "true"
      coolify.domain: "z4s4gkckkkkokc8gccwswwkgw.95.217.187.120.sslip.io"
      traefik.enable: "true"
      traefik.http.routers.taiga-gateway.rule: "Host(`z4s4gkckkkkokc8gccwswwkgw.95.217.187.120.sslip.io`)"
      traefik.http.services.taiga-gateway.loadbalancer.server.port: "80"

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
