version: "3.8"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  taiga-back:
    build: .
    image: taigaio/taiga-back:latest
    environment:
      - DJANGO_SETTINGS_MODULE=settings.local
      - POSTGRES_DB=taiga
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_HOST=taiga-db
      - TAIGA_SECRET_KEY=j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
      - TAIGA_SITES_SCHEME=http
      - TAIGA_SITES_DOMAIN=h80o0wk8skc0coc0ooo8wkc0.95.217.187.120.sslip.io
      - PUBLIC_REGISTER_ENABLED="True"
    volumes:
      - taiga-static-data:/taiga-back/static
      - taiga-media-data:/taiga-back/media
      
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: h80o0wk8skc0coc0ooo8wkc0.95.217.187.120.sslip.io

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment:
      - POSTGRES_DB=taiga
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_HOST=taiga-db
      - TAIGA_SECRET_KEY=j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
      - TAIGA_SITES_SCHEME=http
      - TAIGA_SITES_DOMAIN=xoswc8ckk0kcgwgkgw84gowg.95.217.187.120.sslip.io
      - PUBLIC_REGISTER_ENABLED="True"
    volumes:
      - taiga-static-data:/taiga-back/static
      - taiga-media-data:/taiga-back/media
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: xoswc8ckk0kcgwgkgw84gowg.95.217.187.120.sslip.io

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga123
      RABBITMQ_DEFAULT_VHOST: taiga
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      - TAIGA_URL=http://h80o0wk8skc0coc0ooo8wkc0.95.217.187.120.sslip.io
      - TAIGA_WEBSOCKETS_URL=ws://ju040o4ow800s4ksw08o4k4c4.95.217.187.120.sslip.io
      - PUBLIC_REGISTER_ENABLED=true
    depends_on:
      - taiga-back
    networks:
      - taiga
    labels:
      coolify.domain: g8s0sco8k4w04k4o8coco848.95.217.187.120.sslip.io
      coolify.default: "true"

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      - RABBITMQ_USER=taiga
      - RABBITMQ_PASS=taiga123
      - TAIGA_SECRET_KEY=j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
    depends_on:
      - taiga-events-rabbitmq
    networks:
      - taiga

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga123
      RABBITMQ_DEFAULT_VHOST: taiga
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      - MAX_AGE=360
      - SECRET_KEY=j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
    networks:
      - taiga

  taiga-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./taiga-gateway:/etc/nginx/conf.d:ro
      - taiga-static-data:/taiga-back/static:ro
      - taiga-media-data:/taiga-back/media:ro
    depends_on:
      - taiga-front
      - taiga-back
      - taiga-events
      - taiga-protected
    networks:
      - taiga

volumes:
  taiga-db-data:
  taiga-static-data:
  taiga-media-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
