version: "3.8"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  taiga-back:
    image: taigaio/taiga-back:latest
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
      TAIGA_SITES_SCHEME: http
      TAIGA_SITES_DOMAIN: w8cwkgk4k80kk4w0k4sowk4k.95.217.187.120.sslip.io
      TAIGA_SUBPATH: ""
      PUBLIC_REGISTER_ENABLED: "True"
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
      DEFAULT_FROM_EMAIL: no-reply@example.com
      EMAIL_USE_TLS: "False"
      EMAIL_USE_SSL: "False"
      EMAIL_HOST: smtp.host.example.com
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: user
      EMAIL_HOST_PASSWORD: password
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga123
      ENABLE_TELEMETRY: "False"
    volumes:
      - taiga-static-data:/taiga-back/static
      - taiga-media-data:/taiga-back/media
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: "sgkwckooo4kks0w0s4c4occ8s4.95.217.187.120.sslip.io"

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
      TAIGA_SITES_SCHEME: http
      TAIGA_SITES_DOMAIN: w8cwkgk4k80kk4w0k4sowk4k.95.217.187.120.sslip.io
      TAIGA_SUBPATH: ""
      PUBLIC_REGISTER_ENABLED: "True"
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
      DEFAULT_FROM_EMAIL: no-reply@example.com
      EMAIL_USE_TLS: "False"
      EMAIL_USE_SSL: "False"
      EMAIL_HOST: smtp.host.example.com
      EMAIL_PORT: "587"
      EMAIL_HOST_USER: user
      EMAIL_HOST_PASSWORD: password
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga123
      ENABLE_TELEMETRY: "False"
    volumes:
      - taiga-static-data:/taiga-back/static
      - taiga-media-data:/taiga-back/media
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: "x88csc0k008cass4ococ4sw8c.95.217.187.120.sslip.io"

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga123
      RABBITMQ_DEFAULT_VHOST: taiga
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: "wsk4o48o4oco40ss04okgsso.95.217.187.120.sslip.io"

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://sgkwckooo4kks0w0s4c4occ8s4.95.217.187.120.sslip.io"
      TAIGA_WEBSOCKETS_URL: "ws://ejj8kgccc8o44cwwg8kss80g.95.217.187.120.sslip.io"
      TAIGA_SUBPATH: ""
      PUBLIC_REGISTER_ENABLED: "true"
    networks:
      - taiga
    depends_on:
      - taiga-back
    labels:
      coolify.domain: "w8cwkgk4k80kk4w0k4sowk4k.95.217.187.120.sslip.io"
      coolify.default: "true"

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: taiga
      RABBITMQ_PASS: taiga123
      TAIGA_SECRET_KEY: j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
    networks:
      - taiga
    depends_on:
      - taiga-events-rabbitmq
    labels:
      coolify.domain: "ejj8kgccc8o44cwwg8kss80g.95.217.187.120.sslip.io"

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: secret-erlang-cookie
      RABBITMQ_DEFAULT_USER: taiga
      RABBITMQ_DEFAULT_PASS: taiga123
      RABBITMQ_DEFAULT_VHOST: taiga
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga
    labels:
      coolify.domain: "xggcsss0g8oc4g4o8gokgk4s.95.217.187.120.sslip.io"

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "360"
      SECRET_KEY: j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
    networks:
      - taiga
    labels:
      coolify.domain: "a484c80wcookwss0c8swo8ws.95.217.187.120.sslip.io"

volumes:
  taiga-db-data:
  taiga-static-data:
  taiga-media-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
