version: "3.8"

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: taiga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment:
      # Database
      POSTGRES_DB: taiga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_HOST: taiga-db
      # Taiga settings
      TAIGA_SECRET_KEY: j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl
      TAIGA_SITES_SCHEME: http
      TAIGA_SITES_DOMAIN: oos4w40ogoskw40c8oss804w.95.217.187.120.sslip.io
      # Public registration
      PUBLIC_REGISTER_ENABLED: "True"
      # Email settings
      EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
    volumes:
      - taiga-static-data:/taiga-back/static
      - taiga-media-data:/taiga-back/media
    depends_on:
      - taiga-db
    networks:
      - taiga
    labels:
      traefik.enable: "true"
      traefik.http.routers.taiga-back.rule: "Host(`oos4w40ogoskw40c8oss804w.95.217.187.120.sslip.io`)"
      traefik.http.services.taiga-back.loadbalancer.server.port: "8000"

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "http://oos4w40ogoskw40c8oss804w.95.217.187.120.sslip.io"
      TAIGA_WEBSOCKETS_URL: "ws://oos4w40ogoskw40c8oss804w.95.217.187.120.sslip.io"
      PUBLIC_REGISTER_ENABLED: "true"
    depends_on:
      - taiga-back
    networks:
      - taiga
    labels:
      traefik.enable: "true"
      traefik.http.routers.taiga-front.rule: "Host(`a8ocgwgo40kc4wc48kg0c8g.95.217.187.120.sslip.io`)"
      traefik.http.services.taiga-front.loadbalancer.server.port: "80"
      coolify.default: "true"

volumes:
  taiga-db-data:
  taiga-static-data:
  taiga-media-data:

networks:
  taiga:
