version: "3.5"

x-environment: 
&default-back-environment
  # These environment variables will be used by taiga-back and taiga-async.
  # Database settings
  POSTGRES_DB: "taiga"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres123"
  POSTGRES_HOST: "taiga-db"

  # Taiga settings
  TAIGA_SECRET_KEY: "j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl"
  TAIGA_SITES_SCHEME: "http"
  TAIGA_SITES_DOMAIN: "${TAIGA_DOMAIN}"
  TAIGA_SUBPATH: ""

 # Email settings.
  EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
  DEFAULT_FROM_EMAIL: "no-reply@example.com""
  EMAIL_USE_TLS: "False"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: ""
  EMAIL_PORT: "25"
  EMAIL_HOST_USER: ""
  EMAIL_HOST_PASSWORD: ""

  # Rabbitmq settings
  RABBITMQ_USER: "taiga"
  RABBITMQ_PASS: "taiga123"

 # Telemetry settings
  ENABLE_TELEMETRY: "false"
  PUBLIC_REGISTER_ENABLED: "True"  # Enables public registration in backend

# These volumens will be used by taiga-back and taiga-async.
  x-volumes: &default-back-volumes
  - taiga-static-data:/taiga-back/static
  - taiga-media-data:/taiga-back/media

services:
  taiga-db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: "taiga"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 15s
      retries: 5
      start_period: 3s
    volumes:
      - taiga-db-data:/var/lib/postgresql/data
    networks:
      - taiga

  taiga-back:
    image: taigaio/taiga-back:latest
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async:
    image: taigaio/taiga-back:latest
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: *default-back-environment
    volumes: *default-back-volumes
    networks:
      - taiga
    depends_on:
      taiga-db:
        condition: service_healthy
      taiga-events-rabbitmq:
        condition: service_started
      taiga-async-rabbitmq:
        condition: service_started

  taiga-async-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "taiga-async-rabbitmq-cookie"
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga123"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-async-rabbitmq"
    volumes:
      - taiga-async-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-front:
    image: taigaio/taiga-front:latest
    environment:
      TAIGA_URL: "${TAIGA_SCHEME}://${TAIGA_DOMAIN}"
      TAIGA_WEBSOCKETS_URL: "${WEBSOCKETS_SCHEME}://${TAIGA_DOMAIN}"
      PUBLIC_REGISTER_ENABLED: "true"
    networks:
      - taiga

  taiga-events:
    image: taigaio/taiga-events:latest
    environment:
      RABBITMQ_USER: "taiga"
      RABBITMQ_PASS: "taiga123"
      TAIGA_SECRET_KEY: "j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl"
    networks:
      - taiga
    depends_on:
      taiga-events-rabbitmq:
        condition: service_started

  taiga-events-rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "taiga-events-rabbitmq-cookie"
      RABBITMQ_DEFAULT_USER: "taiga"
      RABBITMQ_DEFAULT_PASS: "taiga123"
      RABBITMQ_DEFAULT_VHOST: "taiga"
    hostname: "taiga-events-rabbitmq"
    volumes:
      - taiga-events-rabbitmq-data:/var/lib/rabbitmq
    networks:
      - taiga

  taiga-protected:
    image: taigaio/taiga-protected:latest
    environment:
      MAX_AGE: "360"
      SECRET_KEY: "j5_e4atjh#mo)f9olk@i!jkk=7e5!$b(yd!v6*0rx$7bq(9lwl"
    networks:
      - taiga

  taiga-gateway:
    image: nginx:1.19-alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.taiga-gateway.rule=PathPrefix(`/`)"
      - "traefik.http.services.taiga-gateway.loadbalancer.server.port=80"
  volumes:
      - ./taiga-gateway/taiga.conf:/etc/nginx/conf.d/default.conf
      - taiga-static-data:/taiga/static
      - taiga-media-data:/taiga/media
  networks:
      - taiga
  depends_on:
      - taiga-front
      - taiga-back
      - taiga-events

volumes:
  taiga-static-data:
  taiga-media-data:
  taiga-db-data:
  taiga-async-rabbitmq-data:
  taiga-events-rabbitmq-data:

networks:
  taiga:
